### PR TITLE
storage: fix GetConnectionbyPublic, throw error on not deleting + add a bunch of tests

### LINKED ISSUE #16: GetConnectionbyPublic does not work
If not exists, it should return ǹil`but i get an Connection from another token.

https://github.com/NoProvider2Push/dbus/blob/832eb6eff90fd67585d5d4d87a86a9e56cbda7d0/storage/storage.go#L64-L67

### PR DESCRIPTION
**Pull request by genofire**
first step add test to validate #16

### CODE REVIEW

File: storage/storage.go [hunk 1]
```diff
@@ -76,7 +83,7 @@ func (s Storage) GetUnequalEndpoint(latestEndpoint string) (ans []*Connection) {
 }
 
 func (s Storage) getFirst(c Connection) *Connection {
-	result := s.db.First(&c)
+	result := s.db.Where(&c).First(&c)
```
Comment (karmanyaahm) [inline storage/storage.go:86]: oh forgetting that is a stupid mistake on my part

**Comment by karmanyaahm** [comment]
thanks for the fix and tests
